### ISSUE TITLE
[FEAT] 컬러 에셋 및 Extension 추가

### ISSUE THREAD

**Issue by Hansangjin98** [Team25s/MOZI-iOS#6]
## 💡 Issue

작업에 사용할 컬러들을 추가합니다.

## 📝 todo

- [x] 컬러 에셋 추가
- [x] UIColor Extension 추가
- [x] Color Extension 추가
